[green_agent]
endpoint = "http://127.0.0.1:9019"
cmd = "python -m prisoners.agents.guard --host 127.0.0.1 --port 9019"

[[participants]]
name = "prisoner_a"
endpoint = "http://127.0.0.1:9018"
cmd = "python -m prisoners.agents.prisoner_betrayer --host 127.0.0.1 --port 9018"

[[participants]]
name = "prisoner_b"
endpoint = "http://127.0.0.1:9017"
cmd = "python -m prisoners.agents.prisoner_cooperator --host 127.0.0.1 --port 9017"

[config]
num_conversations_rounds = 5
num_rounds = 2
